name: Build Application
on: 
  workflow_dispatch : 


jobs:
  build:
    name: Build App
    runs-on : [self-hosted, esp32]
    steps : 
      - name: Check Runner User
        run: whoami
      - name : test_docker
        run: docker run hello-world
        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: esp32h2
          path: '.'
          


      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaires 
          path: |
            build/bootloader/bootloader.bin        
            build/partition_table/partition-table.bin  
            build/My_blink.bin                    