name: Build Application
on: 
  workflow_dispatch : 


jobs:
  build:
    name: Build App
    runs-on : ubuntu-22.04
    steps : 
      - run: echo "tets"
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up ESP-IDF
        run: |
          sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
          python3 --version
          mkdir -p ~/esp
          cd ~/esp
          git clone -b v5.3.1 --recursive https://github.com/espressif/esp-idf.git

          cd ~/esp/esp-idf
          ./install.sh all

          cd ~/esp/esp-idf
          export IDF_GITHUB_ASSETS="dl.espressif.com/github_assets"
          ./install.sh

          . $HOME/esp/esp-idf/export.sh

      
      #- name: esp-idf build
      #  uses: espressif/esp-idf-ci-action@v1
      #  with:
      #    esp_idf_version: v5.3
      #    target: esp32h2
      #    path: '.'

      - run: ls -a

      #- name: Store Artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: My_blink.bin 
      #    path: |
      #      build/My_blink.bin