name: Build Application
on: 
  workflow_dispatch : 


jobs:
  build:
    name: Build App
    runs-on : [self-hosted, esp32]
    steps : 

      - name: Adjust permissions
        run: sudo chmod -R 777 /home/raphael_unix/actions-runner/_work/
      
        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: esp32h2
          path: '.'
          


      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaires 
          path: |
            build/bootloader/bootloader.bin        
            build/partition_table/partition-table.bin  
            build/My_blink.bin  
            
      - name: Flash esp 
        run: |
          ls -a
          . $HOME/esp/esp-idf/export.sh
          esptool.py --chip esp32h2 --baud 460800 write_flash 0x0000 build/bootloader/bootloader.bin 0x10000 build/My_blink.bin 0x8000 build/partition_table/partition-table.bin
        
            
