name: Build Application
on: 
  workflow_dispatch : 


jobs:
  build:
    name: Build App
    runs-on : ubuntu-22.04
    steps : 
      - run: echo "tets"
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3
          target: esp32h2
          path: '.'
          


      - name: Store Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: My_blink.bin 
          path: |
            build/bootloader/bootloader.bin        
            build/partition_table/partition-table.bin  
            build/My_blink.bin                    